# Generated by Django 5.0 on 2023-12-26 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MagicCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('expire_time', models.DateTimeField(verbose_name=datetime.datetime(2023, 12, 26, 3, 14, 50, 634883, tzinfo=datetime.timezone.utc))),
                ('send_count', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
