# Generated by Django 5.0 on 2023-12-26 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magiccode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magiccode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 3, 15, 57, 367032, tzinfo=datetime.timezone.utc)),
        ),
    ]
