# Generated by Django 5.0 on 2023-12-26 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magiccode', '0002_alter_magiccode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magiccode',
            name='code',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='magiccode',
            name='email',
            field=models.EmailField(editable=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='magiccode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 4, 2, 53, 79864, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
